# Generated by Django 3.2.13 on 2022-06-30 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_manager_app', '0002_teamchallenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamchallenge',
            name='customer_accepted_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
