# Generated by Django 3.2.13 on 2022-06-30 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_manager_app', '0004_campaignpurpose'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriteriaPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule', models.CharField(max_length=50)),
                ('point', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
