# Generated by Django 3.2.13 on 2022-06-30 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userprofile_firebase_token'),
        ('line_manager_app', '0005_criteriapoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign_name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('campaign_purpose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='line_manager_app.campaignpurpose')),
                ('criteria_point', models.ManyToManyField(to='line_manager_app.CriteriaPoint')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
