# Generated by Django 3.2.13 on 2022-06-30 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_manager_app', '0006_teamcampaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamcampaign',
            name='criteria_point',
            field=models.ManyToManyField(blank=True, null=True, to='line_manager_app.CriteriaPoint'),
        ),
    ]
