# Generated by Django 3.2.13 on 2022-06-30 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('line_manager_app', '0008_managerconcerntype_managerraiseconcern'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ManagerConcernType',
            new_name='ManagerConcernCategory',
        ),
    ]
