# Generated by Django 3.2.13 on 2022-06-30 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_manager_app', '0009_rename_managerconcerntype_managerconcerncategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managerconcerncategory',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
