# Generated by Django 3.2.13 on 2022-06-30 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('line_manager_app', '0010_alter_managerconcerncategory_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='managerraiseconcern',
            old_name='concern_type',
            new_name='concern_category',
        ),
    ]
