# Generated by Django 3.2.13 on 2022-06-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_manager_app', '0011_rename_concern_type_managerraiseconcern_concern_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengepurpose',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
