# Generated by Django 3.2.13 on 2022-07-01 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_manager_app', '0012_alter_challengepurpose_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamcampaign',
            name='broadcast',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teamchallenge',
            name='broadcast',
            field=models.BooleanField(default=False),
        ),
    ]
