# Generated by Django 3.2.13 on 2022-07-01 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_manager_app', '0014_alter_teamcampaign_criteria_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamchallenge',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
