# Generated by Django 3.2.13 on 2022-07-01 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_manager_app', '0015_teamchallenge_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamcampaign',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teamcampaign',
            name='customer_accepted_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
