# Generated by Django 3.2.13 on 2022-07-01 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_manager_app', '0016_auto_20220701_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamcampaign',
            name='accepted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
