# Generated by Django 3.2.13 on 2022-07-01 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_manager_app', '0017_alter_teamcampaign_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamcampaign',
            name='is_completed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='teamchallenge',
            name='is_completed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
