# Generated by Django 3.2.13 on 2022-07-02 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('line_manager_app', '0018_auto_20220701_1413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamcampaign',
            old_name='accepted',
            new_name='is_accepted',
        ),
        migrations.RenameField(
            model_name='teamcampaign',
            old_name='broadcast',
            new_name='is_broadcasted',
        ),
        migrations.RenameField(
            model_name='teamchallenge',
            old_name='accepted',
            new_name='is_accepted',
        ),
        migrations.RenameField(
            model_name='teamchallenge',
            old_name='broadcast',
            new_name='is_broadcasted',
        ),
    ]
