# Generated by Django 3.2.13 on 2022-07-02 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_manager_app', '0019_auto_20220702_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamcampaign',
            name='is_accepted',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='teamcampaign',
            name='is_broadcasted',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teamcampaign',
            name='is_completed',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='teamchallenge',
            name='is_accepted',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teamchallenge',
            name='is_broadcasted',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teamchallenge',
            name='is_completed',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
