# Generated by Django 3.2.13 on 2022-07-02 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_manager_app', '0020_auto_20220702_1235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamcampaign',
            old_name='is_completed',
            new_name='is_completed_by_customer',
        ),
        migrations.RenameField(
            model_name='teamchallenge',
            old_name='is_completed',
            new_name='is_completed_by_customer',
        ),
        migrations.AddField(
            model_name='teamcampaign',
            name='is_completed_by_manager',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='teamchallenge',
            name='is_completed_by_manager',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
