# Generated by Django 3.2.2 on 2022-07-12 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20220712_1242'),
        ('line_manager_app', '0021_auto_20220702_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerorOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
                ('organiztaion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.organiztaion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ManagerReasonType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason_name', models.CharField(max_length=50)),
                ('status', models.IntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='teamchallenge',
            name='customer_accepted_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamchallenge',
            name='customer_accepted_time',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='teamchallenge',
            name='customer_completed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamchallenge',
            name='customer_completed_time',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='teamchallenge',
            name='manager_created_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamchallenge',
            name='manager_created_time',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='teamchallenge',
            name='manager_updated_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamchallenge',
            name='manager_updated_time',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='ManagerTeamProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, null=True)),
                ('status', models.IntegerField(default=1, null=True)),
                ('manager_org', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='line_manager_app.managerororganization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ManagerJoshReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=200)),
                ('emoji_point', models.IntegerField(blank=True, null=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
                ('reason_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='line_manager_app.managerreasontype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
