# Generated by Django 3.2.2 on 2022-07-22 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('line_manager_app', '0024_industryworktype'),
    ]

    operations = [
        migrations.CreateModel(
            name='KpiName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30, null=True)),
                ('industry_work_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='line_manager_app.industryworktype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
