# Generated by Django 3.2.2 on 2022-07-22 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_userprofile_is_signup'),
        ('line_manager_app', '0025_kpiname'),
    ]

    operations = [
        migrations.AddField(
            model_name='industryworktype',
            name='organiztaion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.organiztaion'),
        ),
    ]
