# Generated by Django 3.2.2 on 2022-07-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_manager_app', '0026_industryworktype_organiztaion'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamchallenge',
            name='industry_work_type',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
