# Generated by Django 3.2.2 on 2022-07-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_manager_app', '0028_teamcampaign_industry_work_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamchallenge',
            name='kpi_name_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
