# Generated by Django 3.2.2 on 2022-07-23 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('line_manager_app', '0031_auto_20220723_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamcampaign',
            name='updated_end_date',
        ),
        migrations.RemoveField(
            model_name='teamchallenge',
            name='updated_end_time',
        ),
    ]
