# Generated by Django 3.2.2 on 2022-07-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_manager_app', '0032_auto_20220723_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='criteriapoint',
            name='kpi_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
