# Generated by Django 3.2.2 on 2022-07-25 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_manager_app', '0034_remove_teamcampaign_kpi_name_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamcampaign',
            name='end_campaign_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamchallenge',
            name='end_challenge_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
