# Generated by Django 3.2.2 on 2022-07-28 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_userprofile_is_active'),
        ('line_manager_app', '0037_teamchallenge_kpi_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpiname',
            name='organiztaion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.organiztaion'),
        ),
        migrations.AlterField(
            model_name='kpiname',
            name='industry_work_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='line_manager_app.industryworktype'),
        ),
    ]
