# Generated by Django 3.2.2 on 2022-08-07 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_manager_app', '0040_teamcampaign_end_campaign_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamchallenge',
            name='end_time_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='teamchallenge',
            name='start_time_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
