# Generated by Django 3.2.2 on 2022-08-07 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_manager_app', '0041_auto_20220807_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamchallenge',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamchallenge',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
