# Generated by Django 3.2.2 on 2022-08-07 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('line_manager_app', '0042_auto_20220807_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamchallenge',
            name='end_datetime',
        ),
        migrations.RemoveField(
            model_name='teamchallenge',
            name='start_datetime',
        ),
    ]
