# Generated by Django 3.2.13 on 2022-06-30 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service_app', '0004_rename_customerconcerntype_customerconcerncategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerraiseconcern',
            old_name='concern_type',
            new_name='concern_category',
        ),
    ]
