# Generated by Django 3.2.13 on 2022-07-02 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('line_manager_app', '0018_auto_20220701_1413'),
        ('accounts', '0017_auto_20220701_1637'),
        ('customer_service_app', '0006_rename_myreward_myrewardpoint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamepoint',
            old_name='point',
            new_name='bonus_point',
        ),
        migrations.RenameField(
            model_name='myrewardpoint',
            old_name='credit',
            new_name='earned_point',
        ),
        migrations.RenameField(
            model_name='myrewardpoint',
            old_name='debit',
            new_name='point_balance',
        ),
        migrations.RenameField(
            model_name='myrewardpoint',
            old_name='point',
            new_name='point_used',
        ),
        migrations.AlterField(
            model_name='gamepoint',
            name='is_won',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.CreateModel(
            name='ChallengePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_won', models.BooleanField(blank=True, default=False, null=True)),
                ('bonus_point', models.ImageField(default=0, upload_to='')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='line_manager_app.teamchallenge')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CampaignPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_won', models.BooleanField(blank=True, default=False, null=True)),
                ('bonus_point', models.ImageField(default=0, upload_to='')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='line_manager_app.teamcampaign')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
