# Generated by Django 3.2.13 on 2022-07-02 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20220702_1148'),
        ('customer_service_app', '0007_auto_20220702_1127'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reason',
            new_name='JoshReason',
        ),
    ]
