# Generated by Django 3.2.2 on 2022-07-06 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_userprofile_role'),
        ('customer_service_app', '0008_rename_reason_joshreason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerraiseconcern',
            name='user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile'),
        ),
    ]
