# Generated by Django 3.2.2 on 2022-07-12 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service_app', '0010_alter_customerraiseconcern_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='joshreason',
            name='manager_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='from_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='to_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
