# Generated by Django 3.2.2 on 2022-07-13 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service_app', '0011_auto_20220712_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='myrewardpoint',
            name='manager_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
