# Generated by Django 3.2.2 on 2022-07-15 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service_app', '0012_myrewardpoint_manager_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joshreason',
            name='reason_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer_service_app.reasontype'),
        ),
    ]
