# Generated by Django 3.2.2 on 2022-07-19 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service_app', '0014_watchtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchtime',
            name='watch_time',
        ),
    ]
