# Generated by Django 3.2.2 on 2022-07-19 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service_app', '0015_remove_watchtime_watch_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchtime',
            name='video_watch_time',
            field=models.IntegerField(null=True),
        ),
    ]
