# Generated by Django 3.2.2 on 2022-07-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service_app', '0016_watchtime_video_watch_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchtime',
            name='video_watch_time',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
