# Generated by Django 3.2.2 on 2022-07-19 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service_app', '0017_alter_watchtime_video_watch_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='watchTime',
        ),
    ]
