# Generated by Django 3.2.2 on 2022-07-23 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service_app', '0020_watchtimedata_game_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchtimedata',
            name='game_name',
        ),
    ]
