# Generated by Django 3.2.2 on 2022-07-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service_app', '0022_customerplayedgame'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerplayedgame',
            name='spent_time',
        ),
        migrations.AddField(
            model_name='customerplayedgame',
            name='is_end',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
