# Generated by Django 3.2.2 on 2022-07-25 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service_app', '0023_auto_20220723_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignpoint',
            name='bonus_point',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='challengepoint',
            name='bonus_point',
            field=models.IntegerField(default=0),
        ),
    ]
