# Generated by Django 3.2.2 on 2022-08-01 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service_app', '0026_watchtimedata_bonus_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerplayedgame',
            name='bonus_point',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='customerplayedgame',
            name='next_availability_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
