# Generated by Django 3.2.2 on 2022-08-02 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('line_manager_app', '0038_auto_20220728_1507'),
        ('customer_service_app', '0029_teamacceptcampaign_teamacceptchallenge'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeamAcceptCampaign',
            new_name='TeamAcceptCampaignHistory',
        ),
        migrations.RenameModel(
            old_name='TeamAcceptChallenge',
            new_name='TeamAcceptChallengeHistory',
        ),
    ]
