# Generated by Django 3.2.2 on 2022-08-03 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service_app', '0031_auto_20220803_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchtimedata',
            name='bonus_point',
        ),
    ]
