# Generated by Django 3.2.2 on 2022-08-03 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service_app', '0032_remove_watchtimedata_bonus_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerplayedgame',
            name='bonus_point',
        ),
    ]
