# Generated by Django 3.2.2 on 2022-08-03 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service_app', '0033_remove_customerplayedgame_bonus_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamepoint',
            name='game_type',
        ),
        migrations.AddField(
            model_name='gamepoint',
            name='game_type_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
