# Generated by Django 3.2.2 on 2022-08-03 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service_app', '0035_watchtimedata_is_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchtimedata',
            name='is_seen',
        ),
    ]
