# Generated by Django 3.2.2 on 2022-08-05 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service_app', '0040_healthmetric_stepstaken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthmetric',
            name='health_metric',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
