# Generated by Django 3.2.2 on 2022-08-05 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service_app', '0041_alter_healthmetric_health_metric'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthmetric',
            name='active',
            field=models.IntegerField(default=0),
        ),
    ]
