# Generated by Django 3.2.2 on 2022-08-05 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service_app', '0043_alter_healthmetric_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningmaterialwatchtimedata',
            name='spent_time_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='readskillandhobbydata',
            name='spent_time_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watchtimedata',
            name='spent_time_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
