# Generated by Django 3.2.2 on 2022-08-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service_app', '0044_auto_20220805_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamepoint',
            name='bonus_point',
            field=models.IntegerField(default=0),
        ),
    ]
