# Generated by Django 3.2.2 on 2022-08-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service_app', '0045_alter_gamepoint_bonus_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthmetric',
            name='weightage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
