# Generated by Django 3.2.2 on 2022-08-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service_app', '0046_healthmetric_weightage'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchtimedata',
            name='bonus_point',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
