# Generated by Django 3.2.2 on 2022-08-23 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service_app', '0048_customerplayedgame_new_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerplayedgame',
            name='new_date',
        ),
    ]
