# Generated by Django 3.2.2 on 2022-08-23 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service_app', '0049_remove_customerplayedgame_new_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='redirectional_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
