# Generated by Django 3.2.2 on 2022-07-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysite',
            name='status',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
