# Generated by Django 3.2.2 on 2022-07-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_user', '0002_companysite_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='WinLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.CharField(max_length=60)),
                ('start_point', models.IntegerField()),
                ('end_point', models.IntegerField()),
                ('status', models.IntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
