# Generated by Django 3.2.2 on 2022-07-18 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_user', '0004_auto_20220718_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningmaterial',
            name='image_data',
            field=models.ImageField(default=0, upload_to='LearningMaterial/image/'),
        ),
        migrations.AddField(
            model_name='learningmaterial',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
