# Generated by Django 3.2.2 on 2022-07-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_user', '0006_leadershiptask_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysite',
            name='image_data',
            field=models.ImageField(default=0, upload_to='CompanySite/image/'),
        ),
        migrations.AddField(
            model_name='companysite',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
