# Generated by Django 3.2.2 on 2022-07-19 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20220712_1242'),
        ('admin_user', '0007_auto_20220718_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50, null=True)),
                ('game_type', models.CharField(choices=[('ACTION', 'Action Game'), ('PUZZLE', 'Puzzle Game'), ('BRAIN', 'Brain Game')], default='ACTION', max_length=20)),
                ('logo', models.ImageField(default=0, upload_to='Game_play/image/')),
                ('start_time', models.DateTimeField(blank=True)),
                ('end_time', models.DateTimeField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organiztaion')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
