# Generated by Django 3.2.2 on 2022-07-19 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_user', '0009_gamename_game_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamename',
            name='logo',
            field=models.ImageField(blank=True, default=0, null=True, upload_to='game_play/image'),
        ),
        migrations.AlterField(
            model_name='learningmaterial',
            name='image_data',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
