# Generated by Django 3.2.2 on 2022-07-22 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_userprofile_is_signup'),
        ('line_manager_app', '0030_teamcampaign_kpi_name_id'),
        ('admin_user', '0010_auto_20220719_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationEmployeeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('emp_code', models.CharField(max_length=60, null=True)),
                ('full_name', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=250, null=True)),
                ('mobile_no', models.IntegerField(null=True)),
                ('gender', models.CharField(max_length=50, null=True)),
                ('designation', models.CharField(max_length=320, null=True)),
                ('location', models.CharField(max_length=120, null=True)),
                ('language', models.CharField(max_length=100, null=True)),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='line_manager_app.manager')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.organiztaion')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='line_manager_app.team')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrganisationPerformanceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kpi_name', models.CharField(max_length=100, null=True)),
                ('kpi_type', models.CharField(max_length=100, null=True)),
                ('kpi_target', models.CharField(max_length=100, null=True)),
                ('target_time_period', models.CharField(max_length=50, null=True)),
                ('kpi_actuals', models.CharField(max_length=50, null=True)),
                ('permormance_date', models.DateTimeField(blank=True, null=True)),
                ('kpi_status', models.IntegerField(null=True)),
                ('organiztaion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.organiztaion')),
                ('organiztaion_employee_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_user.organizationemployeedata')),
            ],
            options={
                'verbose_name': 'OrganisationPerformanceData',
                'verbose_name_plural': 'OrganizationPerformanceData',
            },
        ),
    ]
