# Generated by Django 3.2.2 on 2022-07-22 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_user', '0011_organisationperformancedata_organizationemployeedata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationemployeedata',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='organizationemployeedata',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='organizationemployeedata',
            name='team',
        ),
        migrations.DeleteModel(
            name='OrganisationPerformanceData',
        ),
        migrations.DeleteModel(
            name='OrganizationEmployeeData',
        ),
    ]
