# Generated by Django 3.2.2 on 2022-07-22 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_userprofile_is_signup'),
        ('admin_user', '0012_auto_20220722_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationEmployeeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.organiztaion')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
