# Generated by Django 3.2.2 on 2022-07-23 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_user', '0017_rewardpointsstimulator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamename',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='gamename',
            name='start_time',
        ),
        migrations.AddField(
            model_name='gamename',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
