# Generated by Django 3.2.2 on 2022-07-23 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('line_manager_app', '0032_auto_20220723_1002'),
        ('accounts', '0023_alter_userprofile_is_signup'),
        ('admin_user', '0018_auto_20220723_1225'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrganizationPerformanceData',
            new_name='OrganizationEmployeePerformanceData',
        ),
    ]
