# Generated by Django 3.2.2 on 2022-07-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_user', '0019_rename_organizationperformancedata_organizationemployeeperformancedata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationemployeeperformancedata',
            name='kpi_actuals',
        ),
        migrations.AddField(
            model_name='organizationemployeeperformancedata',
            name='kpi_actual',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organizationemployeeperformancedata',
            name='kpi_target',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
