# Generated by Django 3.2.2 on 2022-07-28 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_userprofile_is_active'),
        ('admin_user', '0020_auto_20220727_1311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companysite',
            options={'verbose_name': 'Company Site | Skill & Hobby'},
        ),
        migrations.AlterModelOptions(
            name='leadershiptask',
            options={'verbose_name': 'Leader ShipTask  | Heath & Fitness'},
        ),
        migrations.AlterModelOptions(
            name='learningmaterial',
            options={'verbose_name': 'Learning Material  | Learning Material'},
        ),
        migrations.AlterModelOptions(
            name='otherlink',
            options={'verbose_name': 'Other Link  | Other Link'},
        ),
        migrations.AddField(
            model_name='organizationemployeedata',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.role'),
        ),
    ]
