# Generated by Django 3.2.2 on 2022-07-28 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_userprofile_is_active'),
        ('admin_user', '0021_auto_20220728_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationemployeedata',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.role'),
        ),
    ]
