# Generated by Django 3.2.2 on 2022-07-29 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_user', '0022_alter_organizationemployeedata_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamename',
            name='benefits',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='gamename',
            name='next_availability_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamename',
            name='purpose',
            field=models.CharField(max_length=220, null=True),
        ),
    ]
