# Generated by Django 3.2.2 on 2022-08-01 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_user', '0023_auto_20220729_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamename',
            name='next_availability_time',
        ),
    ]
