# Generated by Django 3.2.2 on 2022-08-01 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_user', '0024_remove_gamename_next_availability_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamename',
            name='game_time',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
