# Generated by Django 3.2.2 on 2022-08-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_user', '0025_gamename_game_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamename',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
