# Generated by Django 3.2.2 on 2022-08-03 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_user', '0030_organizationemployeedata_organization_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadershiptask',
            name='is_seen',
        ),
    ]
