# Generated by Django 3.2.2 on 2022-08-04 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_user', '0031_remove_leadershiptask_is_seen'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillAndHobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50, null=True)),
                ('image_data', models.ImageField(default=0, upload_to='skill_and_hobby/images/')),
                ('site_url', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.IntegerField(blank=True, default=1, null=True)),
            ],
            options={
                'verbose_name': 'Skill And Hobby | Skill & Hobby',
            },
        ),
        migrations.AlterModelOptions(
            name='companysite',
            options={'verbose_name': 'Company Site | Company Portal'},
        ),
    ]
