# Generated by Django 3.2.2 on 2022-08-04 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_userprofile_device_id'),
        ('admin_user', '0032_auto_20220804_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysite',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.organiztaion'),
        ),
        migrations.AddField(
            model_name='leadershiptask',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.organiztaion'),
        ),
        migrations.AddField(
            model_name='learningmaterial',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.organiztaion'),
        ),
        migrations.AddField(
            model_name='otherlink',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.organiztaion'),
        ),
        migrations.AddField(
            model_name='skillandhobby',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.organiztaion'),
        ),
    ]
