# Generated by Django 3.2.2 on 2022-08-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_user', '0033_auto_20220804_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_module', models.CharField(blank=True, max_length=100, null=True)),
                ('heading', models.TextField()),
                ('activity', models.TextField()),
                ('user_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=150)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('platform', models.CharField(max_length=50)),
                ('platform_icon', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
