# Generated by Django 3.2.2 on 2022-08-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_user', '0036_rename_level_point_pointlevel_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationemployeedata',
            name='full_name',
        ),
        migrations.AddField(
            model_name='organizationemployeeperformancedata',
            name='is_paid',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='organizationemployeedata',
            name='emp_code',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
