# Generated by Django 3.2.2 on 2022-08-16 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_user', '0037_auto_20220816_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationemployeedata',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
