# Generated by Django 3.2.2 on 2022-08-18 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_user', '0038_organizationemployeedata_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatarimage',
            name='is_updated',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
