# Generated by Django 3.2.2 on 2022-08-18 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_user', '0039_avatarimage_is_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avatarimage',
            name='is_updated',
        ),
    ]
