# Generated by Django 3.2.2 on 2022-08-22 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_alter_organiztaion_password'),
        ('admin_user', '0041_organizationtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationtoken',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization', to='accounts.organiztaion'),
        ),
    ]
