# Generated by Django 3.2.2 on 2022-08-22 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_user', '0042_alter_organizationtoken_organization'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrganizationToken',
        ),
    ]
