# Generated by Django 3.2.13 on 2022-06-29 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220629_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organiztaion',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
