# Generated by Django 3.2.13 on 2022-07-01 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configuration',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='organiztaion',
            name='unique_code',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
