# Generated by Django 3.2.13 on 2022-07-01 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20220701_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organiztaion',
            name='unique_code',
        ),
    ]
