# Generated by Django 3.2.13 on 2022-07-01 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_organiztaion_unique_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='organiztaion',
            name='unique_code',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
