# Generated by Django 3.2.13 on 2022-07-01 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_organiztaion_unique_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
