# Generated by Django 3.2.13 on 2022-07-01 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_state_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organiztaion',
            name='assigned_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organiztaion',
            name='assigned_to',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
