# Generated by Django 3.2.13 on 2022-07-01 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_rename_organiztaion_name_organiztaion_organization_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='unique_code',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
