# Generated by Django 3.2.13 on 2022-07-02 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20220701_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_active',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_active_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
