# Generated by Django 3.2.2 on 2022-07-12 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organiztaion',
            options={'verbose_name_plural': 'Organizations'},
        ),
        migrations.RemoveField(
            model_name='organiztaion',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='organiztaion',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='manager_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='team_name',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='manager_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='team_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_active_on',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
