# Generated by Django 3.2.2 on 2022-07-21 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20220712_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_signup',
            field=models.IntegerField(default=1),
        ),
    ]
