# Generated by Django 3.2.2 on 2022-07-28 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_userprofile_is_signup'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_active',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
