# Generated by Django 3.2.2 on 2022-07-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_userprofile_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
