# Generated by Django 3.2.2 on 2022-07-28 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_configuration_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='last_active_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
