# Generated by Django 3.2.2 on 2022-08-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_alter_userprofile_last_active_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar_image_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
