# Generated by Django 3.2.2 on 2022-08-03 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_userprofile_avatar_image_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='device_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
