# Generated by Django 3.2.2 on 2022-08-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_userprofile_device_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='created_by',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
