# Generated by Django 3.2.2 on 2022-08-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_passwordresetotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetotp',
            name='otp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
