# Generated by Django 3.2.2 on 2022-08-18 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_alter_passwordresetotp_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='organiztaion',
            name='password',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
